package com.example.mygame;

import android.app.Activity;
import android.content.Context;
import android.widget.Button;

import java.util.ArrayList;
import java.util.HashMap;

public class GameModel {
    HashMap<Integer, ArrayList<String>> possibleWin = new HashMap<>();
    private ArrayList<Button> grid=new ArrayList<>();
    private Button[][] gridButtons = new Button[5][5];
    public GameModel(Context context, Activity main) {
        for (int row = 0; row < 5; row++) {
            for (int col = 0; col < 5; col++) {
                String buttonId = "button" + row + col;
                int resId = context.getResources().getIdentifier(buttonId, "id", context.getPackageName());
                gridButtons[row][col] = main.findViewById(resId);
            }
        }
    ArrayList<String> temp = new ArrayList<>();
        temp.add("button00,button01,button02");
        temp.add("button00,button11,button22");
        temp.add("button00,button10,button20");
        possibleWin.put(context.getResources().getIdentifier("button00", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button00,button01,button02");
        temp.add("button01,button02,button03");
        temp.add("button01,button12,button23");
        temp.add("button01,button11,button21");
        possibleWin.put(context.getResources().getIdentifier("button01", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button01,button02,button03");
        temp.add("button02,button03,button04");
        temp.add("button02,button13,button24");
        temp.add("button02,button12,button22");
        temp.add("button02,button11,button20");
        temp.add("button00,button01,button02");
        possibleWin.put(context.getResources().getIdentifier("button02", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button02,button03,button04");
        temp.add("button03,button13,button23");
        temp.add("button01,button02,button03");
        temp.add("button03,button12,button21");
        possibleWin.put(context.getResources().getIdentifier("button03", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button02,button03,button04");
        temp.add("button04,button14,button24");
        temp.add("button04,button13,button22");
        possibleWin.put(context.getResources().getIdentifier("button04", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button10,button20,button30");
        temp.add("button00,button10,button20");
        temp.add("button10,button11,button12");
        temp.add("button10,button21,button32");
        possibleWin.put(context.getResources().getIdentifier("button10", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button11,button12,button13");
        temp.add("button11,button21,button31");
        temp.add("button11,button22,button33");
        temp.add("button20,button11,button02");
        temp.add("button01,button11,button21");
        temp.add("button10,button11,button12");
        temp.add("button00,button11,button22");
        possibleWin.put(context.getResources().getIdentifier("button11", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button12,button13,button14");
        temp.add("button12,button22,button32");
        temp.add("button12,button23,button34");
        temp.add("button12,button11,button10");
        temp.add("button12,button21,button30");
        temp.add("button21,button12,button03");
        temp.add("button02,button12,button22");
        temp.add("button11,button12,button13");
        temp.add("button01,button12,button23");
        possibleWin.put(context.getResources().getIdentifier("button12", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button13,button12,button11");
        temp.add("button13,button23,button33");
        temp.add("button13,button22,button31");
        temp.add("button12,button13,button14");
        temp.add("button03,button13,button23");
        temp.add("button04,button13,button22");
        temp.add("button02,button13,button24");
        possibleWin.put(context.getResources().getIdentifier("button13", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button14,button13,button12");
        temp.add("button14,button24,button34");
        temp.add("button04,button14,button24");
        temp.add("button14,button23,button32");
        possibleWin.put(context.getResources().getIdentifier("button14", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button20,button10,button00");
        temp.add("button20,button30,button40");
        temp.add("button20,button11,button02");
        temp.add("button20,button31,button42");
        temp.add("button20,button21,button22");
        temp.add("button10,button20,button30");
        possibleWin.put(context.getResources().getIdentifier("button20", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button21,button11,button01");
        temp.add("button21,button31,button41");
        temp.add("button21,button12,button03");
        temp.add("button21,button32,button43");
        temp.add("button21,button22,button23");
        temp.add("button11,button21,button31");
        temp.add("button20,button21,button22");
        temp.add("button12,button21,button30");
        temp.add("button10,button21,button32");
        possibleWin.put(context.getResources().getIdentifier("button21", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button22,button12,button02");
        temp.add("button22,button32,button42");
        temp.add("button22,button23,button24");
        temp.add("button22,button21,button20");
        temp.add("button22,button13,button04");
        temp.add("button22,button11,button00");
        temp.add("button22,button31,button40");
        temp.add("button22,button33,button44");
        temp.add("button21,button22,button23");
        temp.add("button12,button22,button32");
        temp.add("button13,button22,button31");
        temp.add("button11,button22,button33");
        possibleWin.put(context.getResources().getIdentifier("button22", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button23,button13,button03");
        temp.add("button23,button33,button43");
        temp.add("button23,button12,button01");
        temp.add("button23,button32,button41");
        temp.add("button23,button22,button21");
        temp.add("button12,button23,button34");
        temp.add("button24,button23,button22");
        temp.add("button14,button23,button32");
        temp.add("button13,button23,button33");
        possibleWin.put(context.getResources().getIdentifier("button23", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button24,button14,button04");
        temp.add("button24,button23,button22");
        temp.add("button24,button13,button02");
        temp.add("button24,button33,button42");
        temp.add("button24,button34,button44");
        temp.add("button14,button24,button34");
        possibleWin.put(context.getResources().getIdentifier("button24", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button30,button20,button10");
        temp.add("button30,button31,button32");
        temp.add("button30,button21,button12");
        temp.add("button20,button30,button40");
        possibleWin.put(context.getResources().getIdentifier("button30", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button31,button21,button11");
        temp.add("button31,button22,button13");
        temp.add("button31,button32,button33");
        temp.add("button40,button31,button22");
        temp.add("button21,button31,button41");
        temp.add("button20,button31,button42");
        temp.add("button30,button31,button32");
        possibleWin.put(context.getResources().getIdentifier("button31", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button32,button33,button34");
        temp.add("button32,button22,button12");
        temp.add("button32,button23,button14");
        temp.add("button32,button21,button10");
        temp.add("button32,button31,button30");
        temp.add("button31,button32,button33");
        temp.add("button42,button32,button22");
        temp.add("button41,button32,button23");
        temp.add("button21,button32,button43");
        possibleWin.put(context.getResources().getIdentifier("button32", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button33,button32,button31");
        temp.add("button33,button23,button13");
        temp.add("button33,button22,button11");
        temp.add("button32,button33,button34");
        temp.add("button43,button33,button23");
        temp.add("button44,button33,button22");
        temp.add("button42,button33,button24");
        possibleWin.put(context.getResources().getIdentifier("button33", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button34,button33,button32");
        temp.add("button34,button24,button14");
        temp.add("button24,button34,button44");
        temp.add("button34,button23,button12");
        possibleWin.put(context.getResources().getIdentifier("button34", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button40,button41,button42");
        temp.add("button40,button31,button22");
        temp.add("button40,button30,button20");
        possibleWin.put(context.getResources().getIdentifier("button40", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button40,button41,button42");
        temp.add("button41,button42,button43");
        temp.add("button41,button32,button23");
        temp.add("button41,button31,button21");
        possibleWin.put(context.getResources().getIdentifier("button41", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button41,button42,button43");
        temp.add("button42,button43,button44");
        temp.add("button42,button33,button24");
        temp.add("button42,button32,button22");
        temp.add("button42,button31,button20");
        temp.add("button40,button41,button42");
        possibleWin.put(context.getResources().getIdentifier("button42", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button42,button43,button44");
        temp.add("button43,button33,button23");
        temp.add("button41,button42,button43");
        temp.add("button43,button32,button21");
        possibleWin.put(context.getResources().getIdentifier("button43", "id", context.getPackageName()), temp);
    temp = new ArrayList<>();
        temp.add("button42,button43,button44");
        temp.add("button44,button34,button24");
        temp.add("button44,button33,button22");
        possibleWin.put(context.getResources().getIdentifier("button44", "id", context.getPackageName()), temp);
}

    public HashMap<Integer, ArrayList<String>> getPossibleWin() {
        return possibleWin;
    }

    public ArrayList<Button> getGrid() {
        return grid;
    }

    public Button[][] getGridButtons() {
        return gridButtons;
    }
}
